#####   PROGRAM TABLE  ######

### GET findAll
# http://localhost:2025/api/program

### GET findProgramByProductionId
# GET http://localhost:2025/api/program/production_id/7 

### GET countAll
# GET http://localhost:2025/api/program/count

### GET sortByYrReleased
# GET http://localhost:2025/api/program/sort/yr_released

### sortByTitle
#GET http://localhost:2025/api/program/sort/title

###FIND ACTORS BY PROGRAM TITLE => findActorByProgramTitle
# GET http://localhost:2025/api/actor/title/home%20alone

### GET format
# GET http://localhost:2025/api/program/format/:format

#######    ACTOR TABLE #######

### GET findAll
 # GET http://localhost:2025/api/actor

### GET findById
# GET http://localhost:2025/api/actor/7

### GET findActorByProgramRating
# GET http://localhost:2025/api/actor/actor_rating

### GET sortBYId
# http://localhost:2025/api/actor/sort/1

### GET sortByLast_name
# GET http://localhost:2025/api/actor/sort/last_name

# GET countAllActor 
# GET http://localhost:2025/api/actor/count

### GET actorByForm 
# GET http://localhost:2025/actor-form
 
### findActorByProgramTitle
# GET http://localhost:2025/api/actor/title/home%20alone

### findByLastName
 #GET http://localhost:2025/api/actor/last_name/cage

### sortByLastName 
# GET http://localhost:2025/api/actor/sort/last_name

### countAll
# GET http://localhost:2025/api/actor/count

### SEARCH ACTORs => findActorByProgramRating
# GET http://localhost:2025/api/actor/search/program_rating/PG-13



### findAll
# GET http://localhost:2025/api/actor

### GET findById
# GET http://localhost:2025/api/actor/7


######  POST ######
############ POST ACTOR #####################
### POST create /add new actor
# POST http://localhost:2025/api/actor/create
# {
#    "first_name": "eddie",
#    "last_name": "murphy"
# }


############ UPDATE ACTOR ###################
### UPDATE ACTOR BY ID 141
# PATCH http://localhost:2025/api/actor/update/141

# {
#     "first_name": "kevin",
#     "last_name": "hart"
# }


########  DIRECTOR TABLE  ###########
### findAll
# GET http://localhost:2025/api/director

### GET findById 
# GET http://localhost:2025/api/director/7

 ### countAll 
# GET http://localhost:2025/api/director/count

 ### sortByLast_name
# GET http://localhost:2025/api/director/sort/last_name

### findDirectorByProgramYrReleased 
 # GET http://localhost:2025/api/director/year?year=1990



#################  PRODUCTION TABLE  ################

### GET PRODUCTION  findAll
#GET http://localhost:2025/api/director

### GET PROUCTION ID findById single 
#GET http://localhost:2025/api/director/7

### GET PROCUTION BY NAME 
# GET http://localhost:2025/api/production?production_name=cinet


### GET PRODCUTION BY NAME
#GET http://localhost:2025/api/production



################ STREAMING  #####################

### GET FIND STREMING BY ID 404
 #GET http//localhost:2025/api/streaming_platform/3

### GET ALL STREAMING COUNT  
# GET http://localhost:2025/api/streaming_platform/count

### FIND STREAMING  BY RATING 404
# GET http://localhost:2025/api/streaming/rating?rating=7.0

### GET STREAMING_PLATFORM BY NAME 
#GET http://localhost:2025/api/streaming_platform?by_platform/plex




